### ISSUE TITLE
New Experiment - Data Component

### ISSUE THREAD

**Issue by andrewcz** [cvxgrp/robust_bond_portfolio#2]
Hi ! amazing paper! @phschiele 

If I wanted to try the algorithm on another set of bonds, how would construct the dataset?

Thank you. Andrew

**Comment by phschiele** [comment]
Hi @andrewcz! Thanks a lot!
First, you need to create the cashflow matrix `C`, which is `n x T`, where `n` is the number of bonds and `T` the number of periods.
For example, if one period is six months, and you have a bond with 3% semi annual coupon, $100 principal, and two years to maturity, you would have
```py
C = np.array([[3,3,3,103]])
```
If instead the payment was annual, you'd have
```py
C = np.array([[0,3,0,103]])
```
Combine as many bonds as you want for the cash flow matrix.

Now, you need to define the uncertainty sets for the yields and spreads. In the [tests](https://github.com/cvxgrp/robust_bond_portfolio/blob/main/tests/test_snippets.py), you can find how to set up such an uncertainty set for the trivial case where a maximum element exists. The [example](https://github.com/cvxgrp/robust_bond_portfolio/blob/main/run_examples.py) shows a more realistic example with a confidence ellipsoid based on historic data. We outline other methods in the paper.
Let us know if you have further questions!

**Comment by andrewcz** [comment]
Thank you @phschiele you are a legend!

A couple of questions 

- How do you get the optimal weights from the algorithm?
- Could recommend where to get some more data to test the experiment.
- How do you choose the uncertainty sets?

Thank you!
Andrew

**Comment by phschiele** [comment]
Hi @andrewcz !
Yes, there are 10 different files that all serve as inputs for the optimization. 
We did not export the weights, but they are returned [here](https://github.com/cvxgrp/robust_bond_portfolio/blob/17581e1d1175a472ff50d3449a39730819c44cfb/run_examples.py#LL71C14-L71C14).
So if you change this to 
```py
weights = portfolio_construction(...)
```
you should get a dataframe of the optimal weights.

**Comment by andrewcz** [comment]
Hi @phschiele, cheers for notes above!

Just in terms of defining the data sets, does the datasets represent the following - 

 C.csv - cash flow matrix of bonds described above.
 F.csv - **not sure**
 mean_spreads.csv - the average of the spread of the yield curve.
 mean_yields.csv - the average of the yields.
 mu_joint.csv - **not sure**
 p.csv - **not sure**
 s_nominal.csv - **not sure**
 sigma_joint_inverse.csv - inverse of the covariance matrix(?)
 target_weights.csv - already calculated optimal weights (?)
 y_nominal.csv - **not sure**

Apologies in advance if I have missed something in the paper or the repository. 

Best,
Andrew

**Comment by phschiele** [comment]
Hi @andrewcz, please find my added explanations below. Let me know if you need further information

C.csv - cash flow matrix of bonds described above.
F.csv - Sorry, this was renamed to $Z$ in the paper (section 7.2). It's the linear map that interpolates the yield curve and maps the spreads to the bonds. 
mean_spreads.csv - the average of the spread of the yield curve. -> correct
mean_yields.csv - the average of the yields. -> correct
mu_joint.csv - the historical mean ($\mu^{\text{hist}}$ in 7.2 in the paper)
p.csv - the current prices of the bonds, computed as their cash flows discounted by the corresponding yields and spreads
s_nominal.csv - the most recent spreads
sigma_joint_inverse.csv - inverse of the covariance matrix -> correct
target_weights.csv - The weights as given in the benchmark, the AGGG fund.
y_nominal.csv - the most recent yield curve

**Comment by andrewcz** [comment]
Hi @phschiele thank you! much appreciated for the information above.

I will have a closer look at try and run the experiment. My only other question is where do you get the data from and would i be able to find some different data to try the experiment.

Cheers, Andrew

**Comment by phschiele** [comment]
Hi @andrewcz, just saw there was still a last open question here.
You can construct a cashflow matrix from any source, e.g., you can look up interesting bonds and their maturities and coupons at many financial websites, but I'm sure you already found what you needed back then.

**Comment by andrewcz** [comment]
Thank you sir! Have a great week!
